module.exports = {
  Alpha: require('./Alpha'),
  Animation: require('./Animation'),
  BlendMode: require('./BlendMode'),
  ComputedSize: require('./ComputedSize'),
  Crop: require('./Crop'),
  Depth: require('./Depth'),
  Flip: require('./Flip'),
  GetBounds: require('./GetBounds'),
  Mask: require('./Mask'),
  Origin: require('./Origin'),
  Pipeline: require('./Pipeline'),
  ScaleMode: require('./ScaleMode'),
  ScrollFactor: require('./ScrollFactor'),
  Size: require('./Size'),
  Texture: require('./Texture'),
  TextureCrop: require('./TextureCrop'),
  Tint: require('./Tint'),
  ToJSON: require('./ToJSON'),
  Transform: require('./Transform'),
  TransformMatrix: require('./TransformMatrix'),
  Visible: require('./Visible')
};
